name: Playwright Update Snapshots

on:
  workflow_dispatch:

jobs:
  update-snapshots:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.58.2-noble

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Update Playwright snapshots
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          USERNAME: ${{ secrets.SAUCEDEMO_USERNAME }}
          PASSWORD: ${{ secrets.SAUCEDEMO_PASSWORD }}
        run: npx playwright test tests/snapshots.spec.ts --update-snapshots

      - name: Upload snapshot artifacts
        uses: actions/upload-artifact@v4
        with:
          name: snapshots
          path: tests/snapshots.spec.ts-snapshots

